DROP TABLE IF EXISTS Transferencia;
DROP TABLE IF EXISTS UsuarioNodo;
DROP TABLE IF EXISTS Archivo;
DROP TABLE IF EXISTS Nodo;
DROP TABLE IF EXISTS Usuario;


CREATE TABLE Usuario (
  ID SERIAL PRIMARY KEY,
  NOMBRE VARCHAR(255) NOT NULL,
  EMAIL VARCHAR(255) UNIQUE NOT NULL,
  CONTRASENA VARCHAR(255) NOT NULL,
  FECHA_REGISTRO TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  ULTIMO_LOGIN TIMESTAMP
);

CREATE TABLE Archivo (
  ID SERIAL PRIMARY KEY,
  NOMBRE VARCHAR(255) NOT NULL,
  TAMANO BIGINT NOT NULL,
  TIPO VARCHAR(255) NOT NULL,
  FECHA_SUBIDA TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  ID_USUARIO INT REFERENCES Usuario(ID)
);

CREATE TABLE Nodo (
  ID SERIAL PRIMARY KEY,
  IP_DIR VARCHAR(255) NOT NULL,
  DISPONIBILIDAD BOOLEAN NOT NULL,
  ULTIMA_ACTIVIDAD TIMESTAMP
);

CREATE TABLE UsuarioNodo (
  ID SERIAL PRIMARY KEY,
  ULTIMA_CONEXION TIMESTAMP,
  ID_USUARIO INT REFERENCES Usuario(ID),
  ID_NODO INT REFERENCES Nodo(ID)
);


CREATE TABLE Transferencia (
  ID SERIAL PRIMARY KEY,
  ID_ARCHIVO INT REFERENCES Archivo(ID),
  ID_USUARIO_REC INT REFERENCES Usuario(ID),
  ID_NODO_REC INT REFERENCES Nodo(ID),
  ID_USUARIO_SEND INT REFERENCES Usuario(ID),
  ID_NODO_SEND INT REFERENCES Nodo(ID)
);

